"""Alembic environment for the SaaS tenancy tables.

Deliberately does NOT touch ``schema.sql``/``init_schema()`` (see
``learnings/pgvector_backend.py``) — that remains the self-serve migration
path for the OSS library's ``learnings``/``token_usage``/``agent_learnings``
tables. This Alembic setup owns only the new tenancy/auth/analytics tables
added on top (users, organizations, api_keys, agents, learning_events, ...).

There is no SQLAlchemy ORM/metadata anywhere in this codebase (it's plain
psycopg throughout), so migrations here are raw SQL via ``op.execute()``
rather than autogenerated from a declarative model.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from dotenv import load_dotenv
from sqlalchemy import engine_from_config, pool

load_dotenv()

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Single source of truth for the connection string: the same DATABASE_URL
# env var learnings/pgvector_backend.py and learnings/api/app.py already use.
# The rest of the codebase talks to Postgres via psycopg 3 (no psycopg2
# dependency exists here), so force SQLAlchemy's psycopg3 dialect explicitly.
_dsn = os.environ["DATABASE_URL"]
if _dsn.startswith("postgresql://"):
    _dsn = _dsn.replace("postgresql://", "postgresql+psycopg://", 1)
config.set_main_option("sqlalchemy.url", _dsn)

target_metadata = None


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
